version: 2

project_name: mintop

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download
    - go generate ./...

builds:
  - id: mintop
    main: ./cmd/mintop/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    binary: mintop
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    no_unique_dist_dir: true

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - 'README'
      - Merge pull request
      - Merge branch

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
